name: crc_cicd

on: push

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform -chdir=runtime init

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=runtime plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=runtime apply -auto-approve